### PR TITLE
Migrate the example code to Rescript

### PR DESCRIPTION
**Pull request by dusty-phillips**
@DerivedMate has ported bs-express to Rescript,
but the example is still in Reason.

I've ported it to Rescript syntax by using the
rescript playground to convert from reason to Rescript
and then hand editing the parts that "looked weird".

I have removed the original Reason file, but we could also
leave it in if you think there is benefit to having
two examples.

### CODE REVIEW

**Comment by LaMavia** [comment]
I assume you've tested it, right?

**Comment by dusty-phillips** [comment]
haha, yeah. The tests are throwing the same errors we were seeing on master, but I visually scanned and the status codes are all the same.

**Comment by LaMavia** [comment]
I'll just have a closer look and merge it. I've also thought about submitting this `npm test` error and investigating why it works on travis but not locally.
Thank you for your help

**Comment by dusty-phillips** [comment]
I'm guessing you and I both use Mac and travis is running a Linux. There's a comment in the test file saying that --cookie-jar outputs a comment header that differs between curl versions; it seems it's got some other differences as well.

**Comment by LaMavia** [comment]
I use Ubuntu, but it still might be the case.

**Comment by dusty-phillips** [comment]
If it helps, here's my `curl --version`

```
curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

**Comment by dusty-phillips** [comment]
`curl --cookie-jar - -X $1  -w "\nstatus: %{http_code}" http://localhost:3000$2 | grep "^[^#]" | sed "s/\# Netscape HTTP Cookie File//g" 2>&1 >> $TEST_DATA` almost works for me except it's stripping out one cookie line that actually is expected in the source data file.

**Pull request merged**
